-- PAYMENTS DB
DROP TABLE IF EXISTS payment_network;
CREATE TABLE payment_network (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    network_name VARCHAR(50),
    network_description VARCHAR(255),
    create_date timestamp,
    modify_date timestamp
);
INSERT INTO payment_network (id, network_name, network_description) VALUES ('us-ach', 'ACH', 'Automated Clearing House');
INSERT INTO payment_network (id, network_name, network_description) VALUES ('us-fedwire', 'Fedwire', 'Fedwire Funds Service');
INSERT INTO payment_network (id, network_name, network_description) VALUES ('us-fednow', 'FedNow', 'FedNow Instant Payment RTGS');

DROP TABLE IF EXISTS payment;
CREATE TABLE payment (
    id VARCHAR(50) NOT NULL PRIMARY KEY, -- generated by payment service
    ledger_id VARCHAR(50) NOT NULL, -- ledger ID this payment should be applied to
    payment_network_id VARCHAR(50) NOT NULL, -- ACH, FEDWIRE, FEDNOW, USDC
    service_specific_id VARCHAR(50), -- generated by finsorb-specific service ie ACH Service, FedWire Service, etc
    network_identifier VARCHAR(50), -- network-specific identifier given by payment rail
    current_payment_status VARCHAR(50),
    source_currency VARCHAR(5),
    target_currency VARCHAR(5),
    source_amount NUMERIC,
    target_amount NUMERIC,
    payment_message BYTEA,
    ultimate_originator_entity_id VARCHAR(50),
    ultimate_beneficiary_entity_id VARCHAR(50),
    create_date timestamp,
    modify_date timestamp,
    effective_date timestamp,
    is_batch BOOLEAN, -- ie for ACH, this would be true for the file
    parent_payment_id VARCHAR(50) -- for ACH, each sub-payment would list this file payment as parent
);

DROP TABLE IF EXISTS payment_status_history;
CREATE TABLE payment_status_history (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    payment_id VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50),
    status_detail TEXT,
    create_date timestamp,
    modify_date timestamp
);

DROP TABLE IF EXISTS payment_ledger_entries;
CREATE TABLE payment_ledger_entries (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    payment_id VARCHAR(50) NOT NULL,
    ledger_entry_id VARCHAR(50) NOT NULL,
    create_date timestamp,
    modify_date timestamp
);