server_name=natstwo
listen=4322

accounts {
  $SYS {
    users = [
      { user: "coreuser",
        pass: "$2a$11$ruQvGcilz4xPs7aUPNa.teeLaLt3k1KxKTYrVS9e9M/xBCkzhFooS"
      }
    ]
  }
}

jetstream {
   store_dir=/etc/storage
}

cluster {
  name: CORE
  listen: 0.0.0.0:6322
  routes: [
    nats://nats_one:6222
    nats://nats_three:6422
  ]
}