server_name=natsone
listen=4222

accounts {
  $SYS {
    users = [
      { user: "coreuser",
        pass: "$2a$11$ruQvGcilz4xPs7aUPNa.teeLaLt3k1KxKTYrVS9e9M/xBCkzhFooS"
      }
    ]
  }
}

jetstream {
   store_dir=/etc/storage
}

cluster {
  name: CORE
  listen: 0.0.0.0:6222
  routes: [
    nats://nats_two:6322
    nats://nats_three:6422
  ]
}