version: "3.5"

volumes:
  redis_data:
    driver: local
  pgdb_data:
    driver: local
  nats_one:
    driver: local
  nats_two:
    driver: local
  nats_three:
    driver: local
  temporal-data:
    driver: local

services:
  #############################################
  # CONFIGURATION AND MESSAGING               
  #
  # PORTS:
  #   - 4222 NATS
  #   - 4322 NATS
  #   - 4422 NATS
  #############################################
  otelcollector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    restart: always
    volumes:
    - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
      - "16687:16687"
      - "14317:4317"
      - "14318:4318"
    environment:
      - LOG_LEVEL=debug
    


  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pg_coreledger:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=coreuser"
      - "POSTGRES_PASSWORD=corepassword"
      - "POSTGRES_DB=coreledgerdb"
    volumes:
      - "pgdb_data:/var/lib/postgresql"
      - "./pg_init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d coreledgerdb -U coreuser"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  nats_one:
    container_name: nats01
    image: nats:latest
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
    environment:
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4318"
    command: "-js --config /etc/nats/nats-server.conf"
    volumes:
      - "./nats-config/nats_one:/etc/nats"
      - "nats_one:/etc/storage"

  nats_two:
    container_name: nats02
    image: nats:latest
    restart: always
    ports:
      - 4322:4322
      - 6322:6322
    environment:
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4318"
    command: "-js --config /etc/nats/nats-server.conf"
    volumes:
      - "./nats-config/nats_two:/etc/nats"
      - "nats_two:/etc/storage"

  nats_three:
    container_name: nats03
    image: nats:latest
    restart: always
    ports:
      - 4422:4422
      - 6422:6422
    environment:
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4318"
    command: "-js --config /etc/nats/nats-server.conf"
    volumes:
      - "./nats-config/nats_three:/etc/nats"
      - "nats_three:/etc/storage"

  # Temporal Infra
  temporal:
    image: temporalio/temporal:latest
    container_name: temporal
    ports:
      - 7233:7233
      - 8233:8233
    volumes:
      - temporal-data:/home/temporal
    command: server start-dev --ip 0.0.0.0 --db-filename /home/temporal/temporal.db


  # Compliance and Sanctions
  watchman:
    image: moov/watchman:v0.63.1.arm64
    container_name: watchman
    restart: always
    ports:
      - 18084:8084
    environment:
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4318"
      - "INCLUDED_LISTS=us_ofac,eu_csl,uk_csl,un_csl,us_csl,us_fincen_311,us_non_sdn"
  

  # Address Parser
  postalparse:
    image: openreserveio/postal:latest
    container_name: postal-parse
    restart: always
    ports:
      - 18080:8080

  # Webhooks
  svix:
    image: svix/svix-server
    container_name: svix
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "svix-server healthcheck http://localhost:8071"]
      interval: 1s
      timeout: 1s
      retries: 600
    environment:
      WAIT_FOR: "true" # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      SVIX_DB_DSN: "postgresql://coreuser:corepassword@pg_coreledger/svixdb"
      SVIX_JWT_SECRET: "C023A928-1BAE-4033-8B24-3E43C29D7124"
    ports:
      - "8071:8071"

