package pmtmodel

import (
	"time"

	"github.com/uptrace/bun"
)

var (
	PAYMENT_NETWORK_US_FEDNOW = "us-fednow"
	PAYMENT_NETWORK_US_ACH    = "us-ach"
)

type Payment struct {
	bun.BaseModel `bun:"table:payment"`
	ID            string `bun:"id,pk" json:"id" xml:"id"`

	// Ledger ID this payment should be applied to
	LedgerID string `bun:"ledger_id" json:"ledger_id" xml:"ledger_id"`

	// The ID of the payment network - ACH, FedWire, FedNow, etc
	PaymentNetworkID string `bun:"payment_network_id" json:"payment_network_id" xml:"payment_network_id"`

	// The service specific ID for the network - generated by ACH Service, Payment Service, FedWire Service, etc
	ServiceSpecificID string `bun:"service_specific_id" json:"service_specific_id" xml:"service_specific_id"`

	// ACH Tracer, Fedwire IMAD/OMAD, FedNow Message ID, etc
	NetworkIdentifier string `bun:"network_identifier" json:"network_identifier" xml:"network_identifier"`

	// The status of the payment - NEW, ERROR, PROCESSING, COMPLETED, etc
	CurrentPaymentStatus string `bun:"current_payment_status" json:"current_payment_status" xml:"current_payment_status"`

	// The currency of the source amount
	SourceCurrency string `bun:"source_currency" json:"source_currency" xml:"source_currency"`

	// The currency of the target amount
	TargetCurrency string `bun:"target_currency" json:"target_currency" xml:"target_currency"`

	// The source amount in cents
	SourceAmount int64 `bun:"source_amount" json:"source_amount" xml:"source_amount"`

	// The target amount in cents
	TargetAmount int64 `bun:"target_amount" json:"target_amount" xml:"target_amount"`

	// The ISO 20022 payment message - pacs.008 most likely. base64urlraw(json(pacs.008)) encoded
	PaymentMessage []byte `bun:"payment_message" json:"payment_message" xml:"payment_message"`

	// The Ultimate Originator Entity ID of the Payment
	UltimateOriginatorEntityID string `bun:"ultimate_originator_entity_id" json:"ultimate_originator_entity_id" xml:"ultimate_originator_entity_id"`

	// The Ultimate Beneficiary Entity ID of the Payment
	UltimateBeneficiaryEntityID string `bun:"ultimate_beneficiary_entity_id" json:"ultimate_beneficiary_entity_id" xml:"ultimate_beneficiary_entity_id"`

	// The date the payment was created in the system
	CreateDate time.Time `bun:"create_date" json:"create_date" xml:"create_date"`

	// The Effective Date of the Payment
	EffectiveDate time.Time `bun:"effective_date" json:"effective_date" xml:"effective_date"`

	// The date the payment was last modified in the system
	ModifyDate time.Time `bun:"modify_date" json:"modify_date" xml:"modify_date"`

	// Is this a batch payment instruction (ie US-ACH)?
	IsBatch bool `bun:"is_batch" json:"is_batch" xml:"is_batch"`

	// Is this a child payment instruction?
	ParentPaymentID string `bun:"parent_payment_id" json:"parent_payment_id" xml:"parent_payment_id"`
}

type PaymentStatusHistory struct {
	bun.BaseModel `bun:"table:payment_status_history"`
	ID            string    `bun:"id,pk" json:"id" xml:"id"`
	PaymentID     string    `bun:"payment_id" json:"payment_id" xml:"payment_id"`
	PaymentStatus string    `bun:"payment_status" json:"payment_status"`
	StatusDetail  string    `bun:"status_detail" json:"status_detail"`
	CreateDate    time.Time `bun:"create_date" json:"create_date" xml:"create_date"`
}
