openapi: 3.0.3
info:
  title: "Payments API Service"
  description: |

    This service exposes REST endpoints for the Payments Service

  version: 1.0.0

security:
  - bearerAuth: []
paths:
  /payment:
    post:
      summary: "Post a new Payment for Processing"
      description: |
        Post a new Payment for Processing
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentOrigination"

      responses:
        "200":
          description: "Payment Accepted for Processing"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentOrigination"
        "400":
          description: "Invalid request"

components:
  schemas:
    PaymentOrigination:
      type: object
      properties:
        payment_id:
          type: string
          description: "The payment ID, given to payment by the Payment Service"
        payment_network_id:
          type: string
          description: "The payment network ID"
          enum: ["ach", "fedwire", "fednow", "sepa"]


