server_name=natsthree
listen=4422

accounts {
  $SYS {
    users = [
      { user: "coreuser",
        pass: "$2a$11$ruQvGcilz4xPs7aUPNa.teeLaLt3k1KxKTYrVS9e9M/xBCkzhFooS"
      }
    ]
  }
}

jetstream {
   store_dir=/etc/storage
}

cluster {
  name: CORE
  listen: 0.0.0.0:6422
  routes: [
    nats://nats_one:6222
    nats://nats_two:6322
  ]
}